//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid ItemId { get; set; }
        public string Quantity { get; set; }
        public System.Guid OrderOrderId { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
